\documentclass[a4paper]{report}
\usepackage[latin1]{inputenc}
\usepackage{pdfpages}
\usepackage{hyperref}
\usepackage[french]{babel}
\usepackage{fancyhdr}
\setlength\abovecaptionskip{0pt}
\setlength\belowcaptionskip{10pt}
\pagestyle{fancy}

\lhead{}
\chead{}
\rhead{\bfseries Documents summary
\lfoot{Generated by Orgadoc %%VERSION%%}
\cfoot{}
\rfoot{\thepage}
\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\footrulewidth}{0.4pt}

\newlength{\larg}
\setlength{\larg}{15cm}
\title
    {
      {\rule{\larg}{2mm}}\vspace{7mm}
      \begin{tabular}{p{0.0cm} r}
	& {\Huge {\bf {Documents summary}}} \\
        & \\
        & {\huge Generated by OrgaDoc %%VERSION%%}
      \end{tabular}\\
      \vspace{2mm}
             {\rule{\larg}{2mm}}
             \vspace{2mm} \\
             \vspace{3.5cm}
    }


\begin{document}

%%DOCUMENTS%%
\end{document}
