.TH ORGADOC 1
.SH NAME
orgadoc \- organizes documents from XML descriptions.
.SH SYNOPSIS
.B orgadoc
[\fB\-h\fR \fR]
[\fB\-\-help\fR]
[\fB\-v\fR \fR]
[\fB\-\-version\fR]
[\fB\-t\fR \fR]
[\fB\-\-html\fR]
.IR readme-file
[\fB\-b\fR \fR]
[\fB\-\-bibtex\fR]
.IR readme-file
[\fB\-l\fR \fR]
[\fB\-\-latex\fR]
.IR readme-file
[\fB\-p\fR \fR]
[\fB\-\-plain-text\fR]
.IR readme-file
[\fB\-j\fR \fR]
[\fB\-\-json\fR]
.IR readme-file
[\fB\-d\fR \fR]
[\fB\-\-display-ast\fR]
.IR readme-file
.SH DESCRIPTION
.B orgadoc
uses XML files to describe documents and convert them to a HTML file,
 a Bibtex file, a Latex file, a Plain Text file or a JSON file (in orgadoc syntax).
 Users can also use programs such as grep to combine commands with GNU OrgaDoc.
.SH OPTIONS
.TP
.BR \-h ", " \-\-help\fR
Displays the help text.
.TP
.BR \-v ", " \-\-version\fR
Displays the program version.
.TP
.BR \-t ", " \-\-html\fR
When used as an argument against a readme xml file
 will output a html file.
.TP
.BR \-b ", " \-\-bibtex\fR
When used as an argument against a readme xml file
 will output a bibtex file.
.TP
.BR \-l ", " \-\-latex\fR
When used as an argument against a readme xml file
 will output a latex file.
.TP
.BR \-p ", " \-\-plain-text\fR
When used as an argument against a readme xml file
 will output a plain text file.
.TP
.BR \-j ", " \-\-json\fR
When used as an argument against a readme xml file
 will output a json file.
.TP
.BR \-d ", " \-\-display-ast\fR
When used as an argument against a readme xml file
 will output an ast file.
